// GDS SceneMap — generates docs/scene-map.md from the open scenes, so GAME_CONTEXT never holds hand-written coordinates.
// Rows: every object up to `depth` levels, plus any deeper object carrying a game script (non-Unity MonoBehaviour).
//   unity command gds_scene_map
//   unity command eval "return GDS.SceneMap.WriteJson();"
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace GDS
{
    public static class SceneMap
    {
        const int MaxRows = 400;

        public static string WriteJson(int depth = 2, string scenes = "", string writeTo = "docs/scene-map.md")
        {
            // Extra scenes open additively: nothing in the user's open scenes is discarded. Needed in batchmode (`unity run`).
            foreach (var path in (scenes ?? "").Split(new[] { ',' }, System.StringSplitOptions.RemoveEmptyEntries).Select(x => x.Trim()))
                if (!EditorSceneManager.GetSceneByPath(path).isLoaded && System.IO.File.Exists(System.IO.Path.Combine(Common.ProjectDir, path)))
                    EditorSceneManager.OpenScene(path, OpenSceneMode.Additive);

            var sb = new StringBuilder();
            sb.AppendLine("# Scene map (generated by gds_scene_map — do not edit by hand)");
            sb.AppendLine();
            sb.AppendLine($"Generated: {System.DateTime.Now:yyyy-MM-dd HH:mm}");
            int rows = 0, truncated = 0;
            var listed = new List<string>();

            for (int s = 0; s < EditorSceneManager.sceneCount; s++)
            {
                var scene = EditorSceneManager.GetSceneAt(s);
                if (!scene.isLoaded || (string.IsNullOrEmpty(scene.path) && scene.rootCount == 0)) continue;
                var label = string.IsNullOrEmpty(scene.path) ? "(untitled)" : scene.path;
                listed.Add(label);
                sb.AppendLine();
                sb.AppendLine($"## {label}");
                sb.AppendLine();
                sb.AppendLine("| Path | Pos (x, y, z) | Game scripts | Key components | Children |");
                sb.AppendLine("|---|---|---|---|---|");
                foreach (var root in scene.GetRootGameObjects())
                    Walk(root.transform, 0, depth, sb, ref rows, ref truncated);
            }

            if (truncated > 0) sb.AppendLine($"\n_{truncated} rows omitted (cap {MaxRows})._");
            Common.WriteProjectFile(writeTo, sb.ToString());
            var sceneList = string.Join(",", listed.Select(p => "\"" + p.Replace("\"", "'") + "\""));
            return $"{{\"status\":\"PASS\",\"scenes\":[{sceneList}],\"rows\":{rows},\"omitted\":{truncated},\"out\":\"{writeTo}\"}}";
        }

        static void Walk(Transform t, int level, int depth, StringBuilder sb, ref int rows, ref int truncated)
        {
            var scripts = t.GetComponents<MonoBehaviour>()
                .Where(m => m != null && !IsEngineType(m.GetType()))
                .Select(m => m.GetType().Name).Distinct().ToArray();

            if (level <= depth || scripts.Length > 0)
            {
                if (rows >= MaxRows) truncated++;
                else
                {
                    var key = t.GetComponents<Component>()
                        .Where(c => c != null && !(c is Transform) && !(c is MonoBehaviour && !IsEngineType(c.GetType())))
                        .Select(c => c.GetType().Name)
                        .Where(n => n != "MeshFilter")
                        .Distinct().Take(6);
                    var p = t.position;
                    var path = Common.HierarchyPath(t) + (t.gameObject.activeInHierarchy ? "" : " (inactive)");
                    sb.AppendLine($"| `{path}` | ({p.x:0.##}, {p.y:0.##}, {p.z:0.##}) | {string.Join(", ", scripts)} | {string.Join(", ", key)} | {t.childCount} |");
                    rows++;
                }
            }

            foreach (Transform c in t) Walk(c, level + 1, depth, sb, ref rows, ref truncated);
        }

        static bool IsEngineType(System.Type type)
        {
            var ns = type.Namespace ?? "";
            return ns.StartsWith("UnityEngine") || ns.StartsWith("Unity.") || ns.StartsWith("TMPro") || ns.StartsWith("Cinemachine");
        }
    }
}
